ref: library restructure (#9)
Case-Based/casebased pull request #16
Opened 2024-09-25 14:07 UTC by jonasliendl

2024-09-25 16:22 UTC, jonasliendl commented
@LukasKlockenhoff please review and look for legacy code you would like to have in the restructure.

2024-09-25 21:41 UTC, LukasKlockenhoff requested changes
Bitte alles was nicht leere dateien sind nicht löschen. Ich bin voll für neu schreiben aber dann im jeweiligen Ticket Scope den alten Code durch neuen ersetzen. Wenn wir jetzt alles weg machen haben wir keine referenz und die Arbeit war umsonst.

Die neuen Dateien sind sehr gut und sinnvoll!!

Als kompromiss würde ich sagen wir markieren die Legacy dateien mit

"# DEPRECATED" oder "# REWRITE" oben in der datei.

2024-09-25 21:41 UTC, LukasKlockenhoff commented on casebased/config.py
> +from typing import Callable, Optional, Union
nice 🚀

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/actors/explainer.py
> -"""
Lassen. Die ist neu.

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/__main__.py
> -from casebased.actors.retriever import Retriever
main würde ich auch lassen

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/attribute.py
> -from typing import Any, Optional, Type, Union
Warum das löschen?

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/casebase.py
> -from pathlib import Path
würde zumindest den Code nutzen.

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/explanation.py
> -from typing import List
das ist auch neu und sollte bleiben

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/querycase.py
> -import numpy as np
warum das weg?

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/similarity_measure.py
> -from typing import AnyStr
lassen

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/components/vocabulary.py
> -from typing import List, Union
Ich würde das alles nicht löschen. dann ist die gesamte Arbeit komplett umsonst. Wir schreiben eh viel neu dann sollten wir aber den Code hier lassen für referenz. Das gilt eig für fast alles. Wir brauchen die Klassen ja trotzdem auch wenn wir das über die Instance machen

2024-09-25 21:41 UTC, LukasKlockenhoff commented on src/casebased/utils/errors.py
> -class InvalidAttributeValueError(Exception):
lassen für Error handling

2024-09-25 21:41 UTC, LukasKlockenhoff commented on tests/test_case.py
> -import pytest
auch lassen

2024-09-25 21:41 UTC, LukasKlockenhoff commented on tests/test_case_base_system.py
> +from casebased.config import Configuration
super

2024-09-25 21:41 UTC, LukasKlockenhoff commented on tests/test_similarity_measure.py
> -# content of test_class.py
kann auch dann bleiben.

2024-09-25 21:41 UTC, LukasKlockenhoff commented on tests/test_vocabulary.py
> -import pytest
auch lassen.

2024-09-26 05:22 UTC, jonasliendl commented on src/__main__.py
> -from casebased.actors.retriever import Retriever
Main brauchen wir eigentlich nicht weil wir eine Library machen und kein Executable

2024-09-26 05:54 UTC, jonasliendl commented
Der Legacy Code ist wieder drinnen. Momentan failen noch die Tests wegen des Legacy Codes. Lass uns ab jetzt immer PRs machen, um den Code der anderen zu validieren und sicherzugehen, dass die Tests alle laufen bevor neuer Code auf main gepusht wird.

2024-09-26 06:43 UTC, LukasKlockenhoff approved these changes
LGTM!

2024-09-26 07:36 UTC, merged